[2024-03-21 16:47:04,351: INFO: main: welcome to our custome log]
[2024-03-24 17:03:05,178: INFO: common: yaml file: config\config.yml loaded successfully]
[2024-03-24 17:04:44,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-24 17:04:44,620: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-24 17:04:44,628: INFO: common: created directory at: artifacts]
[2024-03-24 17:04:44,628: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-24 17:04:44,639: INFO: 3363753437: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 17:09:40,719: INFO: 3363753437: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 00:20:50,549: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 00:20:50,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 00:20:51,041: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 00:20:51,093: INFO: common: created directory at: artifacts]
[2024-03-25 00:20:51,293: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 00:20:51,506: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 00:38:13,419: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 00:38:13,435: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 00:38:13,435: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 00:38:13,435: INFO: common: created directory at: artifacts]
[2024-03-25 00:38:13,435: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 00:38:13,435: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 00:48:17,983: INFO: Data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 00:48:20,381: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-25 11:53:01,896: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 11:53:01,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 11:53:02,026: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 11:53:02,064: INFO: common: created directory at: artifacts]
[2024-03-25 11:53:02,075: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 11:53:02,122: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 11:53:40,195: INFO: Data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 11:53:45,148: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-25 12:18:58,454: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 12:18:58,586: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 12:18:58,642: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 12:18:58,693: INFO: common: created directory at: artifacts]
[2024-03-25 12:18:58,709: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 12:18:58,748: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 12:31:53,230: INFO: Data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 12:31:56,157: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-25 12:54:48,355: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-25 15:31:43,863: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 15:31:44,079: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 15:31:44,091: INFO: common: created directory at: artifacts]
[2024-03-25 15:32:21,024: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 15:32:21,033: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 15:32:21,041: INFO: common: created directory at: artifacts]
[2024-03-25 15:35:31,389: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-25 15:35:36,437: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 15:35:36,458: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 15:35:36,461: INFO: common: created directory at: artifacts]
[2024-03-25 15:42:52,544: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 15:42:52,567: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 15:42:52,567: INFO: common: created directory at: artifacts]
[2024-03-25 15:42:52,577: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 15:46:35,015: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 16:32:44,749: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 16:32:44,765: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 16:32:44,765: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 16:32:44,765: INFO: common: created directory at: artifacts]
[2024-03-25 16:32:44,765: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 16:32:44,765: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 16:33:40,484: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 16:33:40,493: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 16:33:40,498: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 16:33:40,501: INFO: common: created directory at: artifacts]
[2024-03-25 16:33:40,504: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 16:33:40,505: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 16:42:13,531: INFO: Data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 16:42:15,488: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-25 16:43:59,369: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 16:43:59,377: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 16:43:59,385: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 16:43:59,385: INFO: common: created directory at: artifacts]
[2024-03-25 16:43:59,389: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 16:43:59,389: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 16:45:14,121: INFO: Data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 16:45:16,462: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-25 16:54:25,718: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 16:54:25,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 16:54:25,736: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 16:54:25,736: INFO: common: created directory at: artifacts]
[2024-03-25 16:54:25,736: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 16:54:25,744: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 16:55:06,123: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 16:55:06,139: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 16:55:06,139: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 16:55:06,139: INFO: common: created directory at: artifacts]
[2024-03-25 16:55:06,139: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 16:55:06,139: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 16:55:24,214: INFO: Data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 16:55:26,191: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-25 16:55:26,191: INFO: main: *******************]
[2024-03-25 16:55:26,191: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-25 16:55:26,232: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 16:55:26,264: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 16:55:26,283: INFO: common: created directory at: artifacts]
[2024-03-25 16:55:26,283: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 16:55:26,283: ERROR: main: name 'PrepareBaseModel' is not defined]
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\main.py", line 20, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model = PrepareBaseModel(config=prepare_base_model_config)
                         ^^^^^^^^^^^^^^^^
NameError: name 'PrepareBaseModel' is not defined
[2024-03-25 16:57:44,518: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-25 16:57:44,534: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 16:57:44,534: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 16:57:44,534: INFO: common: created directory at: artifacts]
[2024-03-25 16:57:44,534: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-25 16:57:44,534: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-25 16:58:09,415: INFO: main: *******************]
[2024-03-25 16:58:09,415: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-25 16:58:09,415: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 16:58:09,415: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 16:58:09,415: INFO: common: created directory at: artifacts]
[2024-03-25 16:58:09,415: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 16:58:09,415: ERROR: main: name 'PrepareBaseModel' is not defined]
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\main.py", line 19, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model = PrepareBaseModel(config=prepare_base_model_config)
                         ^^^^^^^^^^^^^^^^
NameError: name 'PrepareBaseModel' is not defined
[2024-03-25 17:00:37,304: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-25 17:00:38,960: INFO: main: *******************]
[2024-03-25 17:00:38,960: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-25 17:00:38,976: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 17:00:38,976: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 17:00:38,976: INFO: common: created directory at: artifacts]
[2024-03-25 17:00:38,976: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 17:00:38,976: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\main.py", line 19, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-03-25 17:03:30,290: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-25 17:03:32,223: INFO: main: *******************]
[2024-03-25 17:03:32,223: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-25 17:03:32,223: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 17:03:32,239: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 17:03:32,239: INFO: common: created directory at: artifacts]
[2024-03-25 17:03:32,239: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 17:03:32,239: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\main.py", line 19, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-03-25 17:06:14,932: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-25 17:06:16,522: INFO: main: *******************]
[2024-03-25 17:06:16,522: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-25 17:06:16,522: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 17:06:16,522: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 17:06:16,522: INFO: common: created directory at: artifacts]
[2024-03-25 17:06:16,522: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 17:06:16,522: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\main.py", line 19, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-03-25 17:13:03,047: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-25 17:13:04,676: INFO: main: *******************]
[2024-03-25 17:13:04,676: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-25 17:13:04,676: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 17:13:04,676: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 17:13:04,676: INFO: common: created directory at: artifacts]
[2024-03-25 17:13:04,692: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 17:13:04,694: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\main.py", line 19, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-03-25 17:19:30,559: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-25 17:19:32,369: INFO: main: *******************]
[2024-03-25 17:19:32,369: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-25 17:19:32,385: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 17:19:32,385: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 17:19:32,385: INFO: common: created directory at: artifacts]
[2024-03-25 17:19:32,385: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 17:19:32,385: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\main.py", line 19, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-03-25 17:39:53,439: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-25 17:39:56,266: INFO: main: *******************]
[2024-03-25 17:39:56,270: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-25 17:39:56,277: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 17:39:56,290: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 17:39:56,292: INFO: common: created directory at: artifacts]
[2024-03-25 17:39:56,294: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 17:39:56,296: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\main.py", line 19, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-03-25 17:41:35,915: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-25 17:41:37,988: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-25 17:41:37,995: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-25 17:41:38,000: INFO: common: created directory at: artifacts]
[2024-03-25 17:41:38,005: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-25 17:41:39,218: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-25 17:48:23,660: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-28 12:26:48,992: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-28 12:37:08,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 12:37:08,039: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 12:37:08,043: INFO: common: created directory at: artifacts]
[2024-03-28 12:37:08,045: INFO: common: created directory at: artifacts\training]
[2024-03-28 12:43:14,533: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-28 12:43:17,562: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 12:43:17,596: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 12:43:17,604: INFO: common: created directory at: artifacts]
[2024-03-28 12:43:17,607: INFO: common: created directory at: artifacts\training]
[2024-03-28 13:10:45,860: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-28 13:10:47,004: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 13:10:47,020: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 13:10:47,020: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 13:10:47,020: INFO: common: created directory at: artifacts]
[2024-03-28 13:10:47,020: INFO: common: created directory at: artifacts\training]
[2024-03-28 13:35:04,568: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 14:58:08,809: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 14:58:08,824: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 14:58:08,826: INFO: common: created directory at: artifacts]
[2024-03-28 14:59:26,365: INFO: common: json file saved at: scores.json]
[2024-03-28 14:59:39,814: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-28 14:59:41,473: INFO: builder_impl: Assets written to: C:\Users\HP\AppData\Local\Temp\tmpt5ksgrns\model\data\model\assets]
[2024-03-28 15:10:06,433: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 15:10:06,469: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 15:10:06,469: INFO: common: created directory at: artifacts]
[2024-03-28 15:13:44,333: INFO: common: json file saved at: scores.json]
[2024-03-28 15:13:59,231: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-28 15:14:02,337: INFO: builder_impl: Assets written to: C:\Users\HP\AppData\Local\Temp\tmp3g172k9q\model\data\model\assets]
[2024-03-28 15:36:29,057: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-28 15:38:24,175: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-03-28 15:39:36,025: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 19:04:54,267: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-01 19:04:54,272: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-01 19:04:54,276: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-01 19:04:54,277: INFO: common: created directory at: artifacts]
[2024-04-01 19:04:54,279: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-01 19:04:54,280: INFO: Data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-01 19:05:09,960: INFO: Data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-01 19:05:12,016: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-01 19:05:55,578: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 19:05:58,096: INFO: stage_02_prepare_base_model: *******************]
[2024-04-01 19:05:58,096: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-04-01 19:05:58,096: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-01 19:05:58,114: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-01 19:05:58,115: INFO: common: created directory at: artifacts]
[2024-04-01 19:05:58,118: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-01 19:05:58,118: ERROR: stage_02_prepare_base_model: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 28, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "c:\users\hp\onedrive\bureau\complete end to end deep learning project with mlflow,dvc and deployment\kidney_classification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-04-01 19:07:03,054: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 19:07:04,931: INFO: stage_02_prepare_base_model: *******************]
[2024-04-01 19:07:04,931: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-04-01 19:07:04,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-01 19:07:04,956: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-01 19:07:04,956: INFO: common: created directory at: artifacts]
[2024-04-01 19:07:04,962: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-01 19:07:04,962: ERROR: stage_02_prepare_base_model: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 28, in <module>
    prepare_base_model.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "c:\users\hp\onedrive\bureau\complete end to end deep learning project with mlflow,dvc and deployment\kidney_classification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-04-01 19:08:53,682: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 19:09:58,368: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 19:10:00,147: INFO: stage_03_training_model: >>>>>> stage Model Training started <<<<<<]
[2024-04-01 19:10:00,163: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-01 19:10:00,171: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-01 19:10:00,171: INFO: common: created directory at: artifacts]
[2024-04-01 19:10:00,171: INFO: common: created directory at: artifacts\training]
[2024-04-01 19:10:00,179: ERROR: stage_03_training_model: No file or directory found at artifacts\prepare_base_model\base_model_updated.h5]
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_03_training_model.py", line 26, in <module>
    obj.main()
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_03_training_model.py", line 16, in main
    training.get_base_model()
  File "c:\users\hp\onedrive\bureau\complete end to end deep learning project with mlflow,dvc and deployment\kidney_classification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\Model_training.py", line 13, in get_base_model
    self.model = tf.keras.models.load_model(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\prepare_base_model\base_model_updated.h5
[2024-04-01 19:11:31,400: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 19:11:34,380: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-01 19:11:34,402: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-01 19:11:34,410: INFO: common: created directory at: artifacts]
[2024-04-01 19:11:34,419: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-01 19:11:36,850: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-01 19:12:08,878: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 19:12:10,549: INFO: stage_03_training_model: >>>>>> stage Model Training started <<<<<<]
[2024-04-01 19:12:10,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-01 19:12:10,577: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-01 19:12:10,579: INFO: common: created directory at: artifacts]
[2024-04-01 19:12:10,582: INFO: common: created directory at: artifacts\training]
[2024-04-01 19:40:06,430: INFO: stage_03_training_model: >>>>>> stage Model Training completed <<<<<<

x==========x]
[2024-04-01 19:40:20,688: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 19:40:36,717: INFO: stage_04_model_evaluation: >>>>>> stage Model evaluation started <<<<<<]
[2024-04-01 19:40:36,729: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-01 19:40:36,734: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-01 19:40:36,736: INFO: common: created directory at: artifacts]
[2024-04-01 19:42:06,587: INFO: common: json file saved at: scores.json]
[2024-04-01 19:42:10,963: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-01 19:42:12,664: INFO: builder_impl: Assets written to: C:\Users\HP\AppData\Local\Temp\tmpas6rkzly\model\data\model\assets]
[2024-04-01 19:42:33,627: INFO: dir_util: creating C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\3cadeb717dd444c9a7bf44bfab22be4b\artifacts\model\data]
[2024-04-01 19:42:33,627: INFO: dir_util: creating C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\3cadeb717dd444c9a7bf44bfab22be4b\artifacts\model\data\model]
[2024-04-01 19:42:33,627: INFO: dir_util: creating C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\3cadeb717dd444c9a7bf44bfab22be4b\artifacts\model\data\model\assets]
[2024-04-01 19:42:33,642: INFO: dir_util: creating C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\3cadeb717dd444c9a7bf44bfab22be4b\artifacts\model\data\model\variables]
[2024-04-01 19:42:34,032: INFO: stage_04_model_evaluation: >>>>>> stage Model evaluation completed <<<<<<

x==========x]
[2024-04-01 19:44:01,745: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 19:44:02,944: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.43.254:8080]
[2024-04-01 19:44:02,945: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-01 19:44:16,979: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 19:44:16] "GET / HTTP/1.1" 200 -]
[2024-04-01 19:44:47,164: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\hp\onedrive\bureau\complete end to end deep learning project with mlflow,dvc and deployment\kidney_classification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-04-01 19:44:47,213: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 19:44:47] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-01 23:44:28,859: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 23:44:32,967: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.43.254:8080]
[2024-04-01 23:44:32,967: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-01 23:44:38,187: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:44:38] "GET / HTTP/1.1" 200 -]
[2024-04-01 23:44:46,571: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\OneDrive\Bureau\Complete End to End Deep Learning Project With MLFLOW,DVC And Deployment\kidney_Classification\Kidney-Disease-Classification-MLflow-DVC\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\hp\onedrive\bureau\complete end to end deep learning project with mlflow,dvc and deployment\kidney_classification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-04-01 23:44:46,596: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:44:46] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-01 23:46:40,246: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:46:40] "GET / HTTP/1.1" 200 -]
[2024-04-01 23:49:59,818: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-04-01 23:50:03,423: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.43.254:8080]
[2024-04-01 23:50:03,425: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-01 23:50:06,368: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:50:06] "GET / HTTP/1.1" 200 -]
[2024-04-01 23:50:15,617: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:50:15] "POST /predict HTTP/1.1" 200 -]
[2024-04-01 23:50:30,161: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:50:30] "POST /predict HTTP/1.1" 200 -]
[2024-04-01 23:50:35,644: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:50:35] "POST /predict HTTP/1.1" 200 -]
[2024-04-01 23:50:45,893: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:50:45] "POST /predict HTTP/1.1" 200 -]
[2024-04-01 23:50:55,447: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D6B2BE9080> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-04-01 23:50:55,463: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:50:55] "POST /predict HTTP/1.1" 200 -]
[2024-04-01 23:51:18,833: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D6B2BE8C20> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-04-01 23:51:18,851: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:51:18] "POST /predict HTTP/1.1" 200 -]
[2024-04-01 23:51:27,894: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:51:27] "POST /predict HTTP/1.1" 200 -]
[2024-04-01 23:51:38,449: INFO: _internal: 127.0.0.1 - - [01/Apr/2024 23:51:38] "POST /predict HTTP/1.1" 200 -]
